version: '3'
services:

  backend: 
    image: jordipie/backend:latest
    restart: always
    ports:
      - "9090:9090"


  backoffice:
    image: jordipie/backoffice:latest

    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"

  frontend:
    image: jordipie/frontend:latest

    restart: always
    depends_on:
      - backend
    ports:
      - "7070:80"





