version: '3'
services:

  backend: 
    image: jordipie/backend:0.2.2
    restart: always
    ports:
      - "9191:9191"


  backoffice:
    image: jordipie/backoffice:0.1.3

    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"

  frontend:
    image: jordipie/frontend:0.1.6

    restart: always
    depends_on:
      - backend
    ports:
      - "7070:80"





