version: '3'
services:

  backend: 
    image: jordipie/backend:0.1.1
    restart: always
    ports:
      - "9090:9090"


  backoffice:
    image: jordipie/backoffice:0.1.2

    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"





